### ISSUE TITLE
Authentication > New flow > Step "Create User If Unique": can't convert undefined to object

### ISSUE THREAD

**Issue by brsysadmin** [keycloak/keycloak-ui#3470]
### Describe the bug

If I create an authentication flow from scratch + if I add a step "Create User If Unique", I'm not able to edit the settings of this step "Create User If Unique".
Each time I try to edit it, I receive this error:

```
can't convert undefined to object
Press here to refresh and continue
```

The problem is present no matter the name of my authentication flow:
  - with only letters and digits / no special characters except "space" (example: "TEST 01")
  - with only "_" as special character (example: "TEST_01")

However, if I open a built-in Authentication flow (example: first broker login) + if I click on the icon "Settings" for the step "Create User If Unique" it works: I'm able to configure the alias "create unique user config" and the setting "Require Password Update After Registration".

### Version

19.0.2

### Expected behavior

To be able to edit all steps when I create an authentication flow from scratch

### Actual behavior

I receive this error message:

```
can't convert undefined to object
Press here to refresh and continue
```

### How to Reproduce?

1. Create a new Authentication flow from scratch
2. Add a step "Create User If Unique"
3. Click on the icon "Settings"

**Comment by jonkoops** [comment]
Cannot reproduce this in the latest nightly so I assume it has been fixed.

**Comment by jonkoops** [comment]
@brsysadmin feel free to reach out to us if you can still reproduce this.

**Comment by ssilvert** [comment]
If you check the nightly build and you still see a problem we can reopen.

https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by brsysadmin** [comment]
I just updated to Keycloak 19.0.3 and the problem is still present for me

I made some screenshots available here: https://imgur.com/a/6ufuGVd

My Keycloak:
  - is a native instance (not a container)
  - behind Nginx
  - OS: Ubuntu 20.04

My Nginx configuration :

```
# backend active/passive
upstream backend-keycloak-cluster-auth-ap {
    server 192.168.1.4:8180    weight=10    max_fails=3    fail_timeout=15s;
    server 192.168.1.5:8180    weight=10    max_fails=3    fail_timeout=15s    backup;
}

server {
    server_name local-keycloak.domain.com;

    listen 443 ssl;
    include snippets/ssl-domain.com.conf;

    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

    location /robots.txt {
        return 200 "User-agent: *\nDisallow: /";
    }

    access_log /var/log/nginx/access-keycloak.log;
    error_log /var/log/nginx/error-keycloak.log;

    location / {
        rewrite ^ /auth;
    }

    location /auth {
        add_header Cache-Control 'no-store, no-cache';

        proxy_set_header    X-Forwarded-For      $proxy_protocol_addr;
        proxy_set_header    X-Forwarded-Proto    $scheme;
        proxy_set_header    Host                 $host;

        proxy_pass http://backend-keycloak-cluster-auth-ap/auth;
    }
}
```

I don't know if it can help?

**Comment by ssilvert** [comment]
@brsyadmin 19.0.3 only included a few targeted fixes.  What is in the nightly build is what will go into Keycloak 20.0.0.

Are you able to check the nightly build?
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by brsysadmin** [comment]
> @brsyadmin 19.0.3 only included a few targeted fixes. What is in the nightly build is what will go into Keycloak 20.0.0.
> 
> Are you able to check the nightly build? https://github.com/keycloak/keycloak/releases/tag/nightly

Oups, my bad...
I thought nightly was merged in the 19.0.3 :-D

Ok I tested the nightly and the bug seems fixed :)
Sorry to have consumed your time and thank you for the support ;)
