### ISSUE TITLE
Missing roles in users-view

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [keycloak/keycloak-ui#4169]
### Describe the bug

The inherited roles from the `admin`-role of the master realm are not displayed within the ui.

### Version

20.0.2

**Comment by ssilvert** [comment]
@Captain-P-Goldfish I'm seeing all the inherited roles.  Did you uncheck `Hide inherited roles`?

<img width="950" alt="InheritedRoles" src="https://user-images.githubusercontent.com/507202/211872158-560545a3-74b3-43d0-8163-08e9b76eaa51.png">

**Comment by Captain-P-Goldfish** [comment]
In my case it looks like this:

![master-realm-roles](https://user-images.githubusercontent.com/3079540/211908854-ff79e2dd-6b55-4563-82f0-ca797e10ae9f.PNG)


![no-master-realm-roles](https://user-images.githubusercontent.com/3079540/211908883-5be28268-de35-4065-967c-07cdbc4729e9.PNG)

**Comment by ssilvert** [comment]
@Captain-P-Goldfish So you do see the inherited roles?  Is there still something missing?  I don't think I understand your problem.

**Comment by Captain-P-Goldfish** [comment]
Yes you do not see it because my description was inaccurate...
the problem here is that not a single client-role of the master-realm is displayed eventhough the admin-role of the master-realm is assigned to this user.

**Comment by ssilvert** [comment]
OK.  I think I understand now.  When I bring up the `Role mapping` tab for the admin user of master realm, I do see the client roles from `master-realm`.  You can see my results in the image I posted.

Can you try out the nightly build?  Perhaps this is something we already fixed.
https://github.com/keycloak/keycloak/releases/tag/nightly

**Comment by Captain-P-Goldfish** [comment]
I tried the build from 14.01.2023 and I still get the same result.

I did something I should have started with...
I checked the request and response. Seems to be a problem in the backend, not the ui.

![backend-problem](https://user-images.githubusercontent.com/3079540/212532093-db699394-465a-4cdc-8b00-f43e9d46ff67.PNG)

**Comment by ssilvert** [comment]
@Captain-P-Goldfish In that case, I'm going to transfer this issue over to the main repo and assign to a different team.
