### ISSUE TITLE
Horizontal tab scroll back to left doesn't work

### ISSUE THREAD

**Issue by javac9** [keycloak/keycloak-ui#4219]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Using a smaller screen I noticed that, for example, on the "Realm settings" sections (where there are lots of tabs), once you scroll the tab list horizontally to the right, you cannot scroll back to left.

This issue was also present on the previous versions, I just decided to report it now because I've seen that it still hasn't been fixed.

### Version

20.0.3

### Expected behavior

Both scroll arrows allow scrolling in appropriate directions.

### Actual behavior

Scrolling to right works, scrolling back to left does not.

### How to Reproduce?

* In version 20.0.3 (or predecessors) go to Admin Console, then Realm settings using **a smaller screen** or simulate it (to get the scroll arrows shown).
* first scroll to the right
* try to scroll back left

**Comment by ssilvert** [comment]
I have verified this bug.  I seem to remember it being fixed at one time and now it's back.

**Comment by edewit** [comment]
for me this only happens when using the simulated mode, not when the window is actually small

**Comment by javac9** [comment]
Any updates? Just saw it hasn't made it to 21.0.0

**Comment by edewit** [comment]
@javac9 we didn't fix it, I couldn't reproduce it, only happens when I simulate that the screen is small not when it's actually small

**Comment by javac9** [comment]
> @javac9 we didn't fix it, I couldn't reproduce it, it only happens when I simulate that the screen is small not when it's actually small.

What browser? I use latest Chrome, @ssilvert  you wrote that you were able to reproduce the issue, was it in Chrome or another browser?

**Comment by edewit** [comment]
@javac9 are you simulating the browser window with the dev tools, or do you change the physical size?

**Comment by javac9** [comment]
> @javac9 are you simulating the browser window with the dev tools, or do you change the physical size?

I use a laptop with a ultrawide monitor. On the monitor the tabs are all visible so no scrolling. If I drag the window to my laptop, then it shows. So, no simulating but rather real display on 1920x1080 px resolution, with the sizing of 125% (as recommended by Windows).

**Comment by edewit** [comment]
does it start working again when you refresh the screen?

**Comment by javac9** [comment]
> @edewit @javac9 I am on Chrome.
> 
> I discovered something just now. I don't see the bug if the window is maximized on my laptop screen. But I do see the bug if if the window is smaller.

I just tried something similar. I start with the window maximised on my laptop (so smaller, problematic screen). It doesn't work. I then go out of the maximised state, make the screen even smaller but then - it works, but randomly - as I increase and decrease the window it might or might not work.

> does it start working again when you refresh the screen?

I wouldn't say it starts working - after the page is reloaded, the first tabs will get shown even though the last one was previously selected (and actually still is, one needs to scroll to the right to see it selected).

**Comment by edewit** [comment]
created an issue for the patternfly team
